apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: tengen-
namespace: production
commonLabels:
  app: server
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  
